Vagrant.configure("2") do |config|
  # Variáveis
  vm_box = "ubuntu/focal64"
  vm_name = "vagrant-ansible-common"
  vm_hostname = "vagrant-ansible-common"
  vm_memory = "1024"
  vm_cpus = "1"
  vm_provision = "ansible/playbook.yml"

  # Config vm
  config.vm.box = vm_box
  config.vm.hostname = vm_name
  config.vm.define vm_name

  # Config provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = vm_memory
    vb.cpus = vm_cpus
  end

  # Config provision
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = vm_provision
    ansible.verbose = "v"
  end

  # Config network
  config.vm.network "public_network"
end
